/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Dell
 */
public class gaiodien1 extends javax.swing.JFrame {

    /**
     * Creates new form gaiodien1
     */
    public gaiodien1(String CurrentUser) {
        initComponents();
        btnHome.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnHome.setVerticalTextPosition(JLabel.BOTTOM);
        btnemployee.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnemployee.setVerticalTextPosition(JLabel.BOTTOM);
        btnStatistical.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnStatistical.setVerticalTextPosition(JLabel.BOTTOM);
        btncaidat.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btncaidat.setVerticalTextPosition(JLabel.BOTTOM);
        btnupdateacc.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnupdateacc.setVerticalTextPosition(JLabel.BOTTOM);
        btnupload.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnupload.setVerticalTextPosition(JLabel.BOTTOM);
        lblAccount.setText("Xin chào: " + CurrentUser);
        getContentPane().setBackground(Color.WHITE);
        lblAccount.setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelheader = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMid = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnemployee = new javax.swing.JButton();
        btnupload = new javax.swing.JButton();
        btnupdateacc = new javax.swing.JButton();
        btnStatistical = new javax.swing.JButton();
        btncaidat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelheader.setBackground(new java.awt.Color(38, 105, 176));

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("jLabel1");
        lblAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person_120px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÝ BÁN HÀNG");

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelheaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblAccount)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(panelheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelMid.setBackground(new java.awt.Color(255, 255, 255));

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-icon.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHome.setBorderPainted(false);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        btnemployee.setBackground(new java.awt.Color(255, 255, 255));
        btnemployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/management_120px.png"))); // NOI18N
        btnemployee.setText("Employee manager");
        btnemployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnemployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnemployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnemployeeMouseExited(evt);
            }
        });

        btnupload.setBackground(new java.awt.Color(255, 255, 255));
        btnupload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload-icon.png"))); // NOI18N
        btnupload.setText("Upload");
        btnupload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnuploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnuploadMouseExited(evt);
            }
        });

        btnupdateacc.setBackground(new java.awt.Color(255, 255, 255));
        btnupdateacc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnupdateacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-sync-icon_34357.png"))); // NOI18N
        btnupdateacc.setText("Update account");
        btnupdateacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupdateaccMouseExited(evt);
            }
        });

        btnStatistical.setBackground(new java.awt.Color(255, 255, 255));
        btnStatistical.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flow-market-icon.png"))); // NOI18N
        btnStatistical.setText("Statistical");
        btnStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStatisticalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatisticalMouseExited(evt);
            }
        });

        btncaidat.setBackground(new java.awt.Color(255, 255, 255));
        btncaidat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncaidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Settings-icon.png"))); // NOI18N
        btncaidat.setText("Setting");
        btncaidat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncaidatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncaidatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMidLayout = new javax.swing.GroupLayout(panelMid);
        panelMid.setLayout(panelMidLayout);
        panelMidLayout.setHorizontalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMidLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMidLayout.createSequentialGroup()
                .addComponent(btnupdateacc, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btncaidat, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMidLayout.setVerticalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMidLayout.createSequentialGroup()
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMidLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnupdateacc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMidLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncaidat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        getContentPane().add(panelMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 283, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 18, 48));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 203, 1270, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(Color.yellow);
        btnHome.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
            btnHome.setBackground(Color.white);
        btnHome.setForeground(Color.black);  // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnemployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnemployeeMouseEntered
        // TODO add your handling code here:
        btnemployee.setBackground(Color.yellow);
        btnemployee.setForeground(Color.white);
    }//GEN-LAST:event_btnemployeeMouseEntered

    private void btnemployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnemployeeMouseExited
        // TODO add your handling code here:
        btnemployee.setBackground(Color.white);
        btnemployee.setForeground(Color.black);
    }//GEN-LAST:event_btnemployeeMouseExited

    private void btnuploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuploadMouseEntered
        // TODO add your handling code here:
        btnupload.setBackground(Color.yellow);
        btnupload.setForeground(Color.white);
    }//GEN-LAST:event_btnuploadMouseEntered

    private void btnuploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuploadMouseExited
        // TODO add your handling code here:
        btnupload.setBackground(Color.white);
        btnupload.setForeground(Color.black);
    }//GEN-LAST:event_btnuploadMouseExited

    private void btnupdateaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateaccMouseEntered
        // TODO add your handling code here:
        btnupdateacc.setBackground(Color.yellow);
        btnupdateacc.setForeground(Color.white);
    }//GEN-LAST:event_btnupdateaccMouseEntered

    private void btnupdateaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateaccMouseExited
        // TODO add your handling code here:
        btnupdateacc.setBackground(Color.white);
        btnupdateacc.setForeground(Color.black);
    }//GEN-LAST:event_btnupdateaccMouseExited

    private void btnStatisticalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticalMouseEntered
        // TODO add your handling code here:
        btnStatistical.setBackground(Color.yellow);
        btnStatistical.setForeground(Color.white);
    }//GEN-LAST:event_btnStatisticalMouseEntered

    private void btnStatisticalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticalMouseExited
        // TODO add your handling code here:
        btnStatistical.setBackground(Color.white);
        btnStatistical.setForeground(Color.black);
    }//GEN-LAST:event_btnStatisticalMouseExited

    private void btncaidatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaidatMouseEntered
        // TODO add your handling code here:
        btncaidat.setBackground(Color.yellow);
        btncaidat.setForeground(Color.white);
    }//GEN-LAST:event_btncaidatMouseEntered

    private void btncaidatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncaidatMouseExited
        // TODO add your handling code here:
        btncaidat.setBackground(Color.white);
        btncaidat.setForeground(Color.black);
    }//GEN-LAST:event_btncaidatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaiodien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaiodien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaiodien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaiodien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gaiodien1(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnStatistical;
    private javax.swing.JButton btncaidat;
    private javax.swing.JButton btnemployee;
    private javax.swing.JButton btnupdateacc;
    private javax.swing.JButton btnupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelheader;
    // End of variables declaration//GEN-END:variables
}
