/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Dell
 */
public class gaiodien_xanhla extends javax.swing.JFrame {

    Thread dongho;

    /**
     * Creates new form gaiodien1
     */
    public gaiodien_xanhla(String CurrentUser) {
        initComponents();
        btnBill.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnBill.setVerticalTextPosition(JLabel.BOTTOM);
        btnemployee.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnemployee.setVerticalTextPosition(JLabel.BOTTOM);
        btnStatiscal.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnStatiscal.setVerticalTextPosition(JLabel.BOTTOM);
        btnSingout.setHorizontalTextPosition((int) CENTER_ALIGNMENT);
        btnSingout.setVerticalTextPosition(JLabel.BOTTOM);
        lblAccount.setText("Xin chào: " + CurrentUser);
        getContentPane().setBackground(Color.WHITE);
        lblAccount.setHorizontalAlignment(JLabel.CENTER);
        loaddh();
        btnBill.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnBill.setContentAreaFilled(false);
        btnBill.setOpaque(true);
        btnSingout.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnSingout.setContentAreaFilled(false);
        btnSingout.setOpaque(true);
        btnemployee.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnemployee.setContentAreaFilled(false);
        btnemployee.setOpaque(true);
        btnStatiscal.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnStatiscal.setContentAreaFilled(false);
        btnStatiscal.setOpaque(true);
        
    }

   public void loaddh() {
        dongho = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Date d = new Date();
                        SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss aa  dd-mm-yyyy");
                        String time = f.format(d);
                        lbldongho.setText(time);
                        Thread.sleep(1000);
                    } catch (Exception ex) {
                        break;
                    }
                }
            }
        };
        dongho.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelheader = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMid = new javax.swing.JPanel();
        btnBill = new javax.swing.JButton();
        btnemployee = new javax.swing.JButton();
        btnSingout = new javax.swing.JButton();
        btnStatiscal = new javax.swing.JButton();
        lbldongho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelheader.setBackground(new java.awt.Color(26, 52, 158));

        lblAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("jLabel1");
        lblAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person_120px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÝ BÁN HÀNG");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/google_ads_125px.png"))); // NOI18N

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelheaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addComponent(lblAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMid.setBackground(new java.awt.Color(255, 255, 255));

        btnBill.setBackground(new java.awt.Color(242, 242, 242));
        btnBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill_xanhxam.png"))); // NOI18N
        btnBill.setText("Bill management");
        btnBill.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBill.setBorderPainted(false);
        btnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBillMouseExited(evt);
            }
        });
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        btnemployee.setBackground(new java.awt.Color(255, 255, 255));
        btnemployee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/management_xanhxam.png"))); // NOI18N
        btnemployee.setText("Employee manager");
        btnemployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnemployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnemployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnemployeeMouseExited(evt);
            }
        });

        btnSingout.setBackground(new java.awt.Color(255, 255, 255));
        btnSingout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSingout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/export_xanhxam.png"))); // NOI18N
        btnSingout.setText("Sign out");
        btnSingout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSingoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSingoutMouseExited(evt);
            }
        });

        btnStatiscal.setBackground(new java.awt.Color(255, 255, 255));
        btnStatiscal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnStatiscal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/total_sales_xanhxam.png"))); // NOI18N
        btnStatiscal.setText("Statistical");
        btnStatiscal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStatiscalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatiscalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMidLayout = new javax.swing.GroupLayout(panelMid);
        panelMid.setLayout(panelMidLayout);
        panelMidLayout.setHorizontalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMidLayout.createSequentialGroup()
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSingout, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMidLayout.setVerticalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMidLayout.createSequentialGroup()
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMidLayout.createSequentialGroup()
                        .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStatiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSingout, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMidLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbldongho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldongho.setText("lbldongho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillMouseEntered
        btnBill.setBackground(Color.BLUE);
        btnBill.setForeground(Color.white);
        btnBill.setIcon(new ImageIcon(getClass().getResource("/Images/billtrang.png")));

// TODO add your handling code here:
    }//GEN-LAST:event_btnBillMouseEntered

    private void btnBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillMouseExited
        btnBill.setBackground(new Color(242,242,242));
        btnBill.setForeground(Color.black);
        btnBill.setIcon(new ImageIcon(getClass().getResource("/Images/bill_2.png")));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBillMouseExited

    private void btnemployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnemployeeMouseEntered
        // TODO add your handling code here:
        btnemployee.setBackground(Color.BLUE);
        btnemployee.setForeground(Color.white);
        btnemployee.setIcon(new ImageIcon(getClass().getResource("/Images/managementtrang.png")));
    }//GEN-LAST:event_btnemployeeMouseEntered

    private void btnemployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnemployeeMouseExited
        // TODO add your handling code here:
        btnemployee.setBackground(new Color(242,242,242));
       
        btnemployee.setForeground(Color.black);
        btnemployee.setIcon(new ImageIcon(getClass().getResource("/Images/management_2.png")));
    }//GEN-LAST:event_btnemployeeMouseExited

    private void btnSingoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSingoutMouseEntered
        // TODO add your handling code here:
        btnSingout.setBackground(Color.BLUE);
        btnSingout.setForeground(Color.white);
        btnSingout.setIcon(new ImageIcon(getClass().getResource("/Images/export_trang.png")));
    }//GEN-LAST:event_btnSingoutMouseEntered

    private void btnSingoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSingoutMouseExited
        // TODO add your handling code here:
        btnSingout.setBackground(new Color(242,242,242));
        
        btnSingout.setForeground(Color.black);
        btnSingout.setIcon(new ImageIcon(getClass().getResource("/Images/sign_out_22.png")));
    }//GEN-LAST:event_btnSingoutMouseExited

    private void btnStatiscalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatiscalMouseEntered
        // TODO add your handling code here:
        btnStatiscal.setBackground(Color.BLUE);
        btnStatiscal.setForeground(Color.white);
        btnStatiscal.setIcon(new ImageIcon(getClass().getResource("/Images/total_sales_trang.png")));
    }//GEN-LAST:event_btnStatiscalMouseEntered

    private void btnStatiscalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatiscalMouseExited
        // TODO add your handling code here:
        btnStatiscal.setBackground(new Color(242,242,242));
       
        btnStatiscal.setForeground(Color.black);
        btnStatiscal.setIcon(new ImageIcon(getClass().getResource("/Images/total_sales_2.png")));
    }//GEN-LAST:event_btnStatiscalMouseExited

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaiodien_xanhla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaiodien_xanhla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaiodien_xanhla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaiodien_xanhla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gaiodien_xanhla(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnSingout;
    private javax.swing.JButton btnStatiscal;
    private javax.swing.JButton btnemployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelheader;
    // End of variables declaration//GEN-END:variables
}
